project_id = "quclficddptueszrooaa"

[functions.suggest-locations]
verify_jwt = false

[functions.generate-itinerary]
verify_jwt = false

[functions.itinerary-chat]
verify_jwt = false

[functions.generate-share-code]
verify_jwt = true