project_id = "quclficddptueszrooaa"

[functions.suggest-locations]
verify_jwt = true

[functions.generate-itinerary]
verify_jwt = true

[functions.itinerary-chat]
verify_jwt = true

[functions.generate-share-code]
verify_jwt = true

[functions.invite-collaborator]
verify_jwt = true

[functions.generate-invite-link]
verify_jwt = true

[functions.claim-invite]
verify_jwt = true